### ISSUE TITLE
ClinVar model in extensions is not intended for public use

### ISSUE THREAD

**Issue by larrybabb** [broadinstitute/dsp-data-models#29]
I think we should add a readme.md to the root of the ClinVar extensions folder to clarify that it is intended as a stepping stone to get to the final ClinGen representation of the ClinVar data.  It may be quite confusing for folks if they try to use it in this state as it does make certain assumptions and hides a good amount of the data provided by ClinVar's XML.

If you'd like me to write up something to help clarify its purpose and use so that folks don't think its a formal or final version of the DSPCore model let me know.

**Comment by danxmoran** [comment]
I'll add some high-level documentation describing the differences between "core" and "extension" tables to make it more clear. If you want to write up some ClinVar/ClinGen-specific clarifications, we'd be happy to include them too!

**Comment by danxmoran** [comment]
As a (hopefully relevant) tangent: the more I think about it, the less I like storing the data model and Jade schemas together. There will always be drift/purposeful differences between the conceptual model and the end-of-day storage layout, and I don't think the current setup does enough to hammer that home. I'll open a separate issue to discuss.
